export interface CountryCode {
  code: string;
  dialCode: string;
  name: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: 'US', dialCode: '+1', name: 'United States' },
  { code: 'GB', dialCode: '+44', name: 'United Kingdom' },
  { code: 'CA', dialCode: '+1', name: 'Canada' },
  { code: 'IN', dialCode: '+91', name: 'India' },
  { code: 'AU', dialCode: '+61', name: 'Australia' },
  { code: 'DE', dialCode: '+49', name: 'Germany' },
  { code: 'FR', dialCode: '+33', name: 'France' },
  { code: 'IT', dialCode: '+39', name: 'Italy' },
  { code: 'ES', dialCode: '+34', name: 'Spain' },
  { code: 'NL', dialCode: '+31', name: 'Netherlands' },
  { code: 'BE', dialCode: '+32', name: 'Belgium' },
  { code: 'CH', dialCode: '+41', name: 'Switzerland' },
  { code: 'AT', dialCode: '+43', name: 'Austria' },
  { code: 'SE', dialCode: '+46', name: 'Sweden' },
  { code: 'NO', dialCode: '+47', name: 'Norway' },
  { code: 'DK', dialCode: '+45', name: 'Denmark' },
  { code: 'FI', dialCode: '+358', name: 'Finland' },
  { code: 'PL', dialCode: '+48', name: 'Poland' },
  { code: 'IE', dialCode: '+353', name: 'Ireland' },
  { code: 'PT', dialCode: '+351', name: 'Portugal' },
  { code: 'GR', dialCode: '+30', name: 'Greece' },
  { code: 'BR', dialCode: '+55', name: 'Brazil' },
  { code: 'MX', dialCode: '+52', name: 'Mexico' },
  { code: 'AR', dialCode: '+54', name: 'Argentina' },
  { code: 'CL', dialCode: '+56', name: 'Chile' },
  { code: 'CO', dialCode: '+57', name: 'Colombia' },
  { code: 'PE', dialCode: '+51', name: 'Peru' },
  { code: 'ZA', dialCode: '+27', name: 'South Africa' },
  { code: 'EG', dialCode: '+20', name: 'Egypt' },
  { code: 'NG', dialCode: '+234', name: 'Nigeria' },
  { code: 'KE', dialCode: '+254', name: 'Kenya' },
  { code: 'CN', dialCode: '+86', name: 'China' },
  { code: 'JP', dialCode: '+81', name: 'Japan' },
  { code: 'KR', dialCode: '+82', name: 'South Korea' },
  { code: 'SG', dialCode: '+65', name: 'Singapore' },
  { code: 'MY', dialCode: '+60', name: 'Malaysia' },
  { code: 'TH', dialCode: '+66', name: 'Thailand' },
  { code: 'VN', dialCode: '+84', name: 'Vietnam' },
  { code: 'PH', dialCode: '+63', name: 'Philippines' },
  { code: 'ID', dialCode: '+62', name: 'Indonesia' },
  { code: 'BD', dialCode: '+880', name: 'Bangladesh' },
  { code: 'PK', dialCode: '+92', name: 'Pakistan' },
  { code: 'LK', dialCode: '+94', name: 'Sri Lanka' },
  { code: 'AE', dialCode: '+971', name: 'United Arab Emirates' },
  { code: 'SA', dialCode: '+966', name: 'Saudi Arabia' },
  { code: 'IL', dialCode: '+972', name: 'Israel' },
  { code: 'TR', dialCode: '+90', name: 'Turkey' },
  { code: 'RU', dialCode: '+7', name: 'Russia' },
  { code: 'UA', dialCode: '+380', name: 'Ukraine' },
  { code: 'NZ', dialCode: '+64', name: 'New Zealand' },
  { code: 'HK', dialCode: '+852', name: 'Hong Kong' },
  { code: 'TW', dialCode: '+886', name: 'Taiwan' },
].sort((a, b) => a.name.localeCompare(b.name));
